updated TF files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,6 +27,7 @@ jobs:
         run: |
           npm install \
           && npm install mocha
+
       - name: Run tests with Mocha
         run: ./node_modules/.bin/mocha app.js
 
@@ -57,8 +58,7 @@ jobs:
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/qed-challenge:latest
 
       - name: Delete previous keys
-        run: |
-          rm -rf public_key.pub private_key.pem
+        run: rm -rf ec2-terraform/public_key.pub ec2-terraform/private_key.pem
 
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v2
@@ -77,11 +77,7 @@ jobs:
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        run: |
-          terraform apply -auto-approve | tee terraform_output.txt
-
-      - name: List files in directory
-        run: ls -lahtr ec2-terraform/
+        run: terraform apply -auto-approve | tee terraform_output.txt
 
       - name: Wait for Terraform output file to be created
         run: |
@@ -90,36 +86,45 @@ jobs:
           done
 
       - name: Print Terraform Output
-        run: cat ec2-terraform/terraform_output.txt
-
-      - name: Print Private Key Content
-        run: |
-          cat private_key.pem
-          echo "Contents of private_key.pem:"
-          
-      - name: Debug Grep Command
-        run: |
-          grep_result=$(grep -oP 'public_ip = "\K[^"]+' ec2-terraform/terraform_output.txt)
-          echo "Grep Result: $grep_result"
-
-      - name: setting env
-        run: |
-          PUBLIC_IP=$(grep -oP 'public_ip = "\K[^"]+' ec2-terraform/terraform_output.txt)
-          PRIVATE_KEY_PATH=$(grep -oP 'private_key_path = "\K[^"]+' ec2-terraform/terraform_output.txt)
-          echo "::set-output name=public_ip::$PUBLIC_IP"
-          echo "::set-output name=private_key_path::$PRIVATE_KEY_PATH"
+        working-directory: ./ec2-terraform
+        run: cat terraform_output.txt
 
       - name: Extract info
+        working-directory: ./ec2-terraform
         run: |
-          pwd
-          ls -lahtr
-          cat terraform_output.txt
+          PUBLIC_IP=$(grep -oP 'public_ip = "\K[^"]+' terraform_output.txt)
+          PRIVATE_KEY_PATH=$(grep -oP 'private_key_path = "\K[^"]+' terraform_output.txt)
+          echo "Public IP: $PUBLIC_IP"
+          echo "Private Key Path: $PRIVATE_KEY_PATH"
+          
+          # Check if the variables are empty
+          if [[ -z "$PUBLIC_IP" ]]; then
+            echo "Error: PUBLIC_IP is empty"
+            exit 1
+          fi
+          
+          if [[ -z "$PRIVATE_KEY_PATH" ]]; then
+            echo "Error: PRIVATE_KEY_PATH is empty"
+            exit 1
+          fi
+          
+          # Check if the private key file exists
+          if [[ ! -f "$PRIVATE_KEY_PATH" ]]; then
+            echo "Error: Private key file does not exist at $PRIVATE_KEY_PATH"
+            exit 1
+          fi
+          
+          echo "::set-output name=public_ip::$PUBLIC_IP"
+          echo "::set-output name=private_key_path::$PRIVATE_KEY_PATH"
+          echo "Grep Result: $PUBLIC_IP"
           echo "Contents of private_key.pem:"
-          cat private_key.pem
+          cat $PRIVATE_KEY_PATH
 
       - name: SSH into EC2 and deploy
         if: ${{ always() }}
         run: |
+          PUBLIC_IP=$(grep -oP 'public_ip = "\K[^"]+' ec2-terraform/terraform_output.txt)
+          PRIVATE_KEY_PATH=$(grep -oP 'private_key_path = "\K[^"]+' ec2-terraform/terraform_output.txt)
           echo "Public IP: $PUBLIC_IP"
           echo "Private Key Path: $PRIVATE_KEY_PATH"
       
@@ -131,11 +136,3 @@ jobs:
             sudo docker rm qed-challenge || true
             sudo docker run -d --name qed-challenge -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/qed-challenge:latest
           EOF
-
-      - name: Terraform Destroy if Failed
-        if: ${{ failure() }}
-        working-directory: ./ec2-terraform
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        run: terraform destroy -auto-approve
